# ============================================================
# MODULE: mongo_client.py
# PURPOSE: Establishes the MongoDB connection and exposes the three
#          core collections used throughout the pipeline.
# PIPELINE STAGE: Database
# INPUTS: MONGODB_URI environment variable (loaded from .env)
# OUTPUTS: Three collection objects (timesheets, baselines, audit_reports)
#          that other modules import directly
# ============================================================

"""Creates and manages the MongoDB client connection using MONGODB_URI from environment."""

import os
from dotenv import load_dotenv      # reads key=value pairs from a .env file into os.environ
from pymongo import MongoClient     # official MongoDB Python driver
from pymongo.errors import ConnectionFailure  # specific exception for connection problems

# Load the .env file so MONGODB_URI is available via os.getenv().
# This must run before any os.getenv() calls in this file.
load_dotenv()

# Create one shared client for the whole application.
# MongoClient is thread-safe and expensive to construct, so we build it once
# at import time and reuse it everywhere.
_client = MongoClient(os.getenv("MONGODB_URI"))

# Select the "constructiq" database inside the Atlas cluster.
# If it doesn't exist yet, MongoDB creates it automatically on first write.
db = _client["constructiq"]

# --- Collection references ---
# These are the three logical "tables" the pipeline reads and writes.
# Importing modules reference these directly (e.g. `from database.mongo_client import timesheets`).

# Stores one document per ingested daily timesheet row.
# Expected schema fields (populated during ingestion from real HCSS PDFs):
#   project_id   — HCSS project number, e.g. "31062-00"
#   project_name — Human-readable project name, e.g. "Westmorland Elementary School"
#   date         — Shift date (ISO 8601 string, e.g. "2024-03-15")
#   worker_name  — Full name as it appears in HCSS
#   labor_class  — HCSS labor class code (e.g. "SLLS-L1")
#   cost_code    — HCSS cost code string; join key to the baselines collection
#   straight_time_hours — Regular hours worked that shift
#   overtime_hours      — Overtime hours worked that shift
#   equipment_hours     — Hours billed to an equipment asset that shift (0 if none)
#   equipment_type      — Asset name if equipment_hours > 0 (e.g. "SKYTRAK 10054")
#   units_completed     — Production units reported (0 if the row was blank in HCSS)
timesheets = db["timesheets"]

# Stores expected/historical averages per cost_code + labor_class combination.
# The detection modules compare live timesheet data against these baselines.
baselines = db["baselines"]

# Stores the final audit reports generated by the Vertex AI agent,
# one document per audit run.
audit_reports = db["audit_reports"]


def test_connection():
    """Verify the client can actually reach MongoDB Atlas.

    Sends a lightweight 'ping' command to the admin database — the standard
    MongoDB health-check. Prints a success message or the error so the caller
    can see what went wrong without a stack trace.
    """
    try:
        # 'ping' is a no-op command that returns immediately if the server is reachable.
        # Using admin.command (not constructiq) because ping works even on databases
        # where the user has no read/write permissions.
        _client.admin.command("ping")
        print("MongoDB connection successful")
    except ConnectionFailure as e:
        # ConnectionFailure covers authentication errors, network timeouts,
        # and DNS resolution failures — the most common Atlas problems.
        print(f"MongoDB connection failed: {e}")


if __name__ == "__main__":
    # When run directly (`python database/mongo_client.py`), just verify the
    # connection works. This is a quick sanity check before running the full pipeline.
    test_connection()
